SELECT YEAR(SALES.SALES_DATE) AS YEAR, MONTH(SALES.SALES_DATE) AS MONTH, USERS.GENDER, COUNT(DISTINCT USERS.USER_ID) AS USERS
FROM USER_INFO USERS RIGHT JOIN ONLINE_SALE SALES
ON USERS.USER_ID = SALES.USER_ID
WHERE USERS.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY 1, 2, 3