WITH RECURSIVE TEMP AS(
    SELECT 0 AS NUM
    UNION ALL
    SELECT NUM + 1 FROM TEMP
    WHERE NUM < 23
)

SELECT NUM, COUNT(HOUR) AS COUNT
FROM TEMP T LEFT JOIN (
    SELECT HOUR(DATETIME) AS HOUR
    FROM ANIMAL_OUTS
) O
ON T.NUM = O.HOUR
GROUP BY NUM