SELECT P.CATEGORY, M.MAX_PRICE, P.PRODUCT_NAME
FROM FOOD_PRODUCT P RIGHT JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY 1
    ORDER BY 2 DESC
) M
ON P.PRICE = M.MAX_PRICE AND P.CATEGORY = M.CATEGORY